- name: copy_valid_cert_master | copy valid certs to master
  copy:
    src: "{{ apiserver_valid_certs.api_cert_dir }}/{{ apiserver_valid_certs.api_cert_file }}"
    dest: "{{ kube_cert_dir }}/apiserver-valid.pem"
    mode: 0600
  when: apiserver_valid_certs is defined  and inventory_hostname in groups['kube-master']

- name: copy_valid_key_master | copy valid key to master
  copy:
    src: "{{ apiserver_valid_certs.api_cert_dir }}/{{ apiserver_valid_certs.api_cert_key_file }}"
    dest: "{{ kube_cert_dir }}/apiserver-key-valid.pem"
    mode: 0600
  when: apiserver_valid_certs is defined  and inventory_hostname in groups['kube-master']

- name: debug_cert | debug crt
  debug: 
    msg: "{{apiserver_valid_certs}} {{inventory_hostname}} {{ apiserver_valid_certs.api_cert_ca_file }}"

- name: copy_valid_ca_node | copy valid ca to k8s nodes
  copy:
    src: "{{ apiserver_valid_certs.api_cert_dir }}/{{ apiserver_valid_certs.api_cert_ca_file }}"
    dest: "{{ kube_cert_dir }}/apiserver-ca-valid.pem
    mode: 0600
  when: apiserver_valid_certs is defined 

- name: Gen_certs | check certificate permissions
  file:
    path={{ kube_cert_dir }}
    group={{ kube_cert_group }}
    owner=kube
    recurse=yes

- name: Gen_certs | set permissions on keys
  shell: chmod 0600 {{ kube_cert_dir}}/*key.pem
  when: inventory_hostname in groups['kube-master']
  changed_when: false
